// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using movie_api.Contexts;

namespace movie_api.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20220726115805_CreateStudiosTable")]
    partial class CreateStudiosTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("movie_api.Models.MovieSchedules", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime")
                        .HasColumnName("date");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_at");

                    b.Property<string>("end_time")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("end_time");

                    b.Property<int>("movie_id")
                        .HasColumnType("int")
                        .HasColumnName("movie_id");

                    b.Property<double>("price")
                        .HasColumnType("double")
                        .HasColumnName("price");

                    b.Property<string>("start_time")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("start_time");

                    b.Property<int>("studio_id")
                        .HasColumnType("int")
                        .HasColumnName("studio_id");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("id")
                        .HasName("PK_movie_schedules");

                    b.HasIndex("movie_id");

                    b.HasIndex("studio_id");

                    b.ToTable("movie_schedules");
                });

            modelBuilder.Entity("movie_api.Models.MovieTags", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_at");

                    b.Property<int>("movie_id")
                        .HasColumnType("int")
                        .HasColumnName("movie_id");

                    b.Property<int>("tag_id")
                        .HasColumnType("int")
                        .HasColumnName("tag_id");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("id")
                        .HasName("PK_movie_tags");

                    b.HasIndex("movie_id");

                    b.HasIndex("tag_id");

                    b.ToTable("movie_tags");
                });

            modelBuilder.Entity("movie_api.Models.Movies", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_at");

                    b.Property<string>("overview")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("overview");

                    b.Property<DateTime>("play_until")
                        .HasColumnType("datetime")
                        .HasColumnName("play_until");

                    b.Property<string>("poster")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("poster");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("id")
                        .HasName("PK_movies");

                    b.ToTable("movies");
                });

            modelBuilder.Entity("movie_api.Models.OrderItems", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_at");

                    b.Property<int>("movie_schedule_id")
                        .HasColumnType("int")
                        .HasColumnName("movie_schedule_id");

                    b.Property<int>("order_id")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<double>("price")
                        .HasColumnType("double")
                        .HasColumnName("price");

                    b.Property<int>("qty")
                        .HasColumnType("int")
                        .HasColumnName("qty");

                    b.Property<double>("sub_total_price")
                        .HasColumnType("double")
                        .HasColumnName("sub_total_price");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("id")
                        .HasName("PK_order_items");

                    b.HasIndex("movie_schedule_id");

                    b.HasIndex("order_id");

                    b.ToTable("order_items");
                });

            modelBuilder.Entity("movie_api.Models.Orders", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_at");

                    b.Property<int>("payment_method")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("payment_method");

                    b.Property<double>("total_item_price")
                        .HasColumnType("double")
                        .HasColumnName("total_item_price");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("user_id")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("id")
                        .HasName("PK_orders");

                    b.HasIndex("user_id");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("movie_api.Models.Studios", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_at");

                    b.Property<int>("seat_capacity")
                        .HasColumnType("int")
                        .HasColumnName("seat_capacity");

                    b.Property<int>("studio_number")
                        .HasColumnType("int")
                        .HasColumnName("studio_number");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("id")
                        .HasName("PK_studios");

                    b.ToTable("studios");
                });

            modelBuilder.Entity("movie_api.Models.Tags", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_at");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("id")
                        .HasName("PK_tags");

                    b.ToTable("tags");

                    b.HasData(
                        new
                        {
                            id = 1,
                            created_at = new DateTime(2022, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            name = "Scifi"
                        },
                        new
                        {
                            id = 2,
                            created_at = new DateTime(2022, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            name = "Fantasy"
                        });
                });

            modelBuilder.Entity("movie_api.Models.Users", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("activation_key")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("activation_key");

                    b.Property<string>("avatar")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("avatar");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_at");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<int>("is_admin")
                        .HasColumnType("int")
                        .HasColumnName("is_admin");

                    b.Property<int>("is_confirmed")
                        .HasColumnType("bool")
                        .HasColumnName("is_confirmed");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("id")
                        .HasName("PK_users");

                    b.ToTable("users");
                });

            modelBuilder.Entity("movie_api.Models.MovieSchedules", b =>
                {
                    b.HasOne("movie_api.Models.Movies", "movie")
                        .WithMany()
                        .HasForeignKey("id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("movie_api.Models.Studios", "studio")
                        .WithMany()
                        .HasForeignKey("id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("movie_api.Models.Movies", null)
                        .WithMany()
                        .HasForeignKey("movie_id")
                        .HasConstraintName("FK_movie_schedules_movies")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("movie_api.Models.Studios", null)
                        .WithMany()
                        .HasForeignKey("studio_id")
                        .HasConstraintName("FK_movie_schedules_studios")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("movie");

                    b.Navigation("studio");
                });

            modelBuilder.Entity("movie_api.Models.MovieTags", b =>
                {
                    b.HasOne("movie_api.Models.Movies", "movie")
                        .WithMany()
                        .HasForeignKey("id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("movie_api.Models.Tags", "tag")
                        .WithMany()
                        .HasForeignKey("id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("movie_api.Models.Movies", null)
                        .WithMany()
                        .HasForeignKey("movie_id")
                        .HasConstraintName("FK_movie_tags_movies")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("movie_api.Models.Tags", null)
                        .WithMany()
                        .HasForeignKey("tag_id")
                        .HasConstraintName("FK_movie_tags_tags")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("movie");

                    b.Navigation("tag");
                });

            modelBuilder.Entity("movie_api.Models.OrderItems", b =>
                {
                    b.HasOne("movie_api.Models.MovieSchedules", "movieSchedule")
                        .WithMany()
                        .HasForeignKey("id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("movie_api.Models.Orders", "order")
                        .WithMany()
                        .HasForeignKey("id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("movie_api.Models.MovieSchedules", null)
                        .WithMany()
                        .HasForeignKey("movie_schedule_id")
                        .HasConstraintName("FK_order_items_movie_schedules")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("movie_api.Models.Orders", null)
                        .WithMany()
                        .HasForeignKey("order_id")
                        .HasConstraintName("FK_order_items_orders")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("movieSchedule");

                    b.Navigation("order");
                });

            modelBuilder.Entity("movie_api.Models.Orders", b =>
                {
                    b.HasOne("movie_api.Models.Users", "user")
                        .WithMany()
                        .HasForeignKey("id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("movie_api.Models.Users", null)
                        .WithMany()
                        .HasForeignKey("user_id")
                        .HasConstraintName("FK_orders_users")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("user");
                });
#pragma warning restore 612, 618
        }
    }
}
